image: node:latest

stages:
  - deploy

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

deployment:
  stage: deploy
  script:
    - ssh deploy@lestaubiere.bramvanosta.com /var/www/lestaubiere/scripts/installStaging.sh
  only:
    - master
  environment: staging
