export const REQUEST_MAP_DIRECTION = 'REQUEST_MAP_DIRECTION';
export const FETCHED_MAP_DIRECTION_SUCCESS = 'FETCHED_MAP_DIRECTION_SUCCESS';
export const FETCHED_MAP_DIRECTION_NOT_FOUND = 'FETCHED_MAP_DIRECTION_NOT_FOUND';
export const FETCHED_MAP_DIRECTION_ERROR = 'FETCHED_MAP_DIRECTION_ERROR';
