export const REQUEST_CONTACT_SUBMIT = 'REQUEST_CONTACT_SUBMIT';
export const FETCHED_CONTACT_SUBMIT_SUCCESS = 'FETCHED_CONTACT_SUBMIT_SUCCESS';
export const FETCHED_CONTACT_SUBMIT_ERROR = 'FETCHED_CONTACT_SUBMIT_ERROR';
export const RESET_CONTACT_FORM = 'RESET_CONTACT_FORM';
