export const REQUEST_CONTACT_SUBMIT = 'REQUEST_CONTACT_SUBMIT';
export const FETCHED_CONTACT_SUBMIT_SUCCESS = 'FETCHED_CONTACT_SUBMIT_SUCCESS';
export const FETCHED_CONTACT_SUBMIT_ERROR = 'FETCHED_CONTACT_SUBMIT_ERROR';
export const SET_NAME = 'SET_NAME';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_MESSAGE = 'SET_MESSAGE';
